### PR TITLE
DM-32226: Replace `pipe.base.timeMethod` with `utils.timer`

### PR DESCRIPTION
**Pull request by andy-slac**

### CODE REVIEW

**Review by timj — APPROVED** [review]
If you want to merge this you will have to either disable the CI requirement or switch to github action.

**Comment by andy-slac** [comment]
OK, I'll just drop `.travis.yaml`, not sure that it's spending time on GA for the package that is not used.

**Comment by timj** [comment]
I turned off the CI requirement.

**Comment by timj** [comment]
@andy-slac I imagine you saw that I had already dealt with your merge problem. No, you would not have been able to merge on the CLI because the push would have been refused because the CI status check would have been required (until I removed that requirement).

**Pull request merged**
